name: CI Code Quality & Build Check

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main

jobs:
  verify:
    name: Lint, Typecheck & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run TypeScript Type Check
        run: npx tsc --noEmit

      - name: Run Production Build
        run: npm run build
        env:
          MONGODB_URI: "mongodb://Admin:200431001370@ac-0sooljd-shard-00-00.yvrefxj.mongodb.net:27017,ac-0sooljd-shard-00-01.yvrefxj.mongodb.net:27017,ac-0sooljd-shard-00-02.yvrefxj.mongodb.net:27017/Freelance-DB?ssl=true&replicaSet=atlas-4rloqf-shard-0&authSource=admin&appName=Cluster0"
          JWT_SECRET: "68ef54cfc83263f8594516fca8573db89895a79492c91084ea99da8af605a7fc"